apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot.appname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
data:
  application.yaml: |-
{{ .Values.appConfig | nindent 4 }}
