apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot.appname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_HOST: "{{ include "springboot.dbname" . }}"
  MONGODB_PORT: "{{ .Values.mongodb.port | default 27017 }}"
  MONGODB_DATABASE: "{{ .Values.mongodb.auth.database }}"
  MONGODB_USERNAME: "{{ .Values.mongodb.auth.username }}"
  MONGODB_PASSWORD: "{{ .Values.mongodb.auth.password }}"
