apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot.appname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      targetPort: http
  selector:
    {{- include "springboot.selectorLabels" . | nindent 4 }}