{{- if not .Values.mongodb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot.dbname" . }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.auth.database | quote }}
  MONGO_USERNAME: {{ required "App DB username is required" .Values.mongodb.auth.username }}
  MONGO_PASSWORD: {{ required "App DB password is required" .Values.mongodb.auth.password }}
{{- end }}
