apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "springboot.dbname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  serviceName: {{ include "springboot.dbname" . }}
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "springboot.dbname" . }}
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "springboot.dbname" . }}
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
          envFrom:
            - secretRef:
                name: {{ default (include "springboot.dbname" .) .Values.mongodb.auth.existingSecret }}
            {{- if .Values.mongodb.envConfigMap }}
            - configMapRef:
                name: {{ include "springboot.dbname" . }}
            {{- end }}
          args:
            - "--bind_ip_all"
          {{- with .Values.mongodb.probes.livenessProbe }}
          livenessProbe:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mongodb.probes.readinessProbe }}
          readinessProbe:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mongodb.probes.startupProbe }}
          startupProbe:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
        {{- if .Values.mongodb.persistence.storageClass }}
        storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
        {{- end }}
